

image: php:5.6

before_script:
- bash Tests/gitlab-ci/docker_install.sh > /dev/null
- echo "date.timezone = Europe/Paris" >/usr/local/etc/php/php.ini
- curl --silent --show-error https://getcomposer.org/installer | php
- php composer.phar install --prefer-dist

test:Fonctionnel:
  script:
  - Tests/bin/behat Tests/  --config Tests/behat.yml
